cc_binary(
  name = "asis",
  srcs = ["asis/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "base_object",
  srcs = ["base_object/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "init",
  srcs = ["init/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "nested",
  srcs = ["nested/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "one_func",
  srcs = ["one_func/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "one_func_cond",
  srcs = ["one_func_cond/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "one_func_cond2",
  srcs = ["one_func_cond2/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "one_memfn",
  srcs = ["one_memfn/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "serialization",
  srcs = ["serialization/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "split_func",
  srcs = ["split_func/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "split_memfn",
  srcs = ["split_memfn/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "streams",
  srcs = ["streams/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "traits-ex",
  srcs = ["traits-ex/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "traits",
  srcs = ["traits/main.cpp"],
  deps = ["@yas//:yas"]
)

cc_binary(
  name = "xor-stream",
  srcs = ["xor-stream/main.cpp"],
  deps = ["@yas//:yas"]
)
